### ISSUE TITLE
Integration not loading any lights

### ISSUE THREAD

**Issue by thijsvanbloemendaal** [jankrib/ha-xcomfort-bridge#1]
Hi,

I was happy to see there was a xcomfort integration, so first of all thanks for putting in the effort to build one. But after installing it it seems to timeout finding any light, or devices for that matter. So I see just a integration with no entities at all.

Also I have no authkey on the back of the controller, so I used the password. What Uri and headers are used underneath? Maybe I can check something.
Thanks in advance!

**Comment by oywino** [comment]
This integration is not compatible with thecontroller. It is designed to work only with the xComfort Bridge.
https://www.eaton.com/bg/en-gb/catalog/residential/xcomfort-bridge.html
You will find th auth key on the back of the bridge.
