### ISSUE TITLE
Power sensor roports wrong unit

### ISSUE THREAD

**Issue by jankrib** [jankrib/ha-xcomfort-bridge#17]
We report in W for `energy`. It must either be `Wh` for `device_class` `energy` or W for `power`

See https://developers.home-assistant.io/docs/core/entity/sensor

```
(<class 'custom_components.xcomfort_bridge.sensor.XComfortPowerSensor'>) is using native unit of measurement 'W' which is not a valid unit for the device class ('energy') it is using; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
```

**Comment by TomStarren** [comment]
I changed several things in `sensor.py` and it seems to remove the errors.

Line 21 to 25:
```from homeassistant.const import (
    ENERGY_KILO_WATT_HOUR,
    PERCENTAGE,
    POWER_WATT,
    ENERGY_WATT_HOUR,
)
```

Then search for all mentions of `POWER_WATT` and change it to `ENERGY_WATT_HOUR`

**Comment by oywino** [comment]
Great job @TomStarren 
Looks like this is working 👍
