### ISSUE TITLE
Warning after HA upgrade to 2023.2.1

### ISSUE THREAD

**Issue by oywino** [jankrib/ha-xcomfort-bridge#18]
After upgrading HA to 2023.2.1 I get this warning:

``Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for xcomfort_bridge using this method at custom_components/xcomfort_bridge/__init__.py, line 38: hass.config_entries.async_setup_platforms(entry, PLATFORMS)
``

**Comment by TomStarren** [comment]
Changing line 38 in `__init__.py` seems to work

From:
`hass.config_entries.async_setup_platforms(entry, PLATFORMS)`

To:
`await hass.config_entries.async_forward_entry_setups (entry, PLATFORMS)`

**Comment by oywino** [comment]
Indeed - that did help! Thank you so much, but how did you come to think of this as a solution? And what exactly was the problem? Is you fix needed as a result of some braking change in HA? Or is your fix just a 'workaround' ?

**Comment by oywino** [comment]
Apparently, it seems this fix hasn't been included yet ?
