### ISSUE TITLE
One step further....

### ISSUE THREAD

**Issue by oywino** [jankrib/ha-xcomfort-bridge#20]
I have now been able to make the `cover.py` part of the integrqation it work -partially. I can now close and stop the screens, but I cannot open them. I have been debugging for weeks without being able to figure out why `open `fails and everything else works. I need some help, please.

The first thing I did to to resolve the HA error message: `AttributeError: can't set attribute 'device_class'` was to remove the line: 
`self.device_class = DEVICE_CLASS_SHADE`

That took me one step further. Now HA reported a new error message:
`AttributeError: 'HASSXComfortShade' object has no attribute '_attr_is_closed'` so I added the following definition:

```
@property
    def is_closed(self) -> bool:
        """Return if the cover is closed."""
        return self._state == "closed"
```

That did help. I can now `close `and `stop `the screens, but not `open `them. This is how it looks in HA:

![image](https://user-images.githubusercontent.com/18447119/235372428-970e4e9b-c142-4dfe-a67f-a5f15f0abaea.png)

The reason for this problem seems to be because the state of the screen isn't passed correctly to HA. It remains `open `all the time even when it is closed. So the `open `command (arrow) is inactive unless I manually set its state to `closed` in HA. Then the up arrow becomes active. But pressing it does nothing except resetting the state back to `open`.

This problem seems to be very similar to what is described here: 
https://github.com/home-assistant/core/issues/65690

**Comment by jankrib** [comment]
This should be fixed now
