### ISSUE TITLE
New FW version from Eaton broke the integration

### ISSUE THREAD

**Issue by oywino** [jankrib/ha-xcomfort-bridge#25]
I updated to the new firmware version that Eaton released today, and sadly it broke your integration Jan. I really hope you can help us all out now.

**Comment by jankrib** [comment]
Will ahve a look. I'm updating now.

**Comment by jankrib** [comment]
That's strange. No issues for me. Do you have an error message in the log?

**Comment by oywino** [comment]
I do not because HA was restarted (which clears the log as far as I know). But what you say is very good news, indicating that perhaps I made some mistake. I am on a business trip this week but I will try again this coming weekend and then send you a copy of the log.  Many thanks for stepping in, Jan.

**Comment by oywino** [comment]
Here is my log:

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/xcomfort_bridge/hub.py:51
Integration: Eaton xComfort Bridge (documentation, issues)
First occurred: 11:10:28 (1 occurrences)
Last logged: 11:10:28

Error setting up entry 192.168.1.101 for xcomfort_bridge
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xcomfort_bridge/__init__.py", line 36, in async_setup_entry
    await hub.load_devices()
  File "/config/custom_components/xcomfort_bridge/hub.py", line 51, in load_devices
    devs = await self.bridge.get_devices()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/xcomfort/bridge.py", line 282, in get_devices
    await self.wait_for_initialization()
  File "/usr/local/lib/python3.11/site-packages/xcomfort/bridge.py", line 272, in wait_for_initialization
    await asyncio.sleep(0.1)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 639, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError: Global task timeout

**Comment by alexbrasetvik** [comment]
+1 on things (seemingly) working after updating the bridge.

**Comment by jankrib** [comment]
Could it be that it changed IP address after update?

**Comment by oywino** [comment]
Yes, I think that was the problem. I configured the xComfort Bridge first using a SIM-card based router. Then I moved it to a new fiber connected router once this was properly installed. Obviously the new DHCP server handed out from a new IP adresse range.
I've re-installed everything, and it works now. 
Many thanks for taking the time to reply @jankrib

**Comment by jankrib** [comment]
Good to hear that it works now.
