### ISSUE TITLE
Make Identifier field voluntary and fix the readme

### ISSUE THREAD

**Issue by jankrib** [jankrib/ha-xcomfort-bridge#9]
This field is useful for those who care about unique ids. It should be easy to skip, though. And the way it's described in the readme doesn't make sense.

**Comment by skela** [comment]
Yeah it's just a nickname or reference. Useful for some, I like being able to name my things so 😂

It was meant to be optional sure, I thought it defaulted to use the ip address if missing.

**Comment by jankrib** [comment]
"XComfort Bridge" makes sense as a default.

**Comment by jankrib** [comment]
Fixed this is the last build
